In [1]:
import numpy as np


print("Hello, World!")

Hello, World!


### Numpy Arrays

In [2]:
X = np.array([90.1, 85.5, 92.3])
print(X)

print(type(X))
print(X.shape)
print(X.dtype)

[90.1 85.5 92.3]
<class 'numpy.ndarray'>
(3,)
float64


In [3]:
print(np.ones(shape=10))
print(np.zeros(shape=10))
print(np.random.rand(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.00414107 0.31205172 0.51814165 0.94715839 0.9801419  0.80278476
 0.97002532 0.99381675 0.48707798 0.73027103]


### Numpy Arrays As Vectors

In [4]:
v_1 = np.array([1, 2, 3])
v_2 = np.array([4, 5, 6])
v_3 = v_1 + v_2 # element-wise addition
print(v_3)

[5 7 9]


In [5]:
v_4 = 10 * v_1  # scalar multiplication
print(v_4)

[10 20 30]


In [6]:
v_5 = v_1 * v_2 # element-wise multiplication
print(v_5)

[ 4 10 18]


In [7]:
print(np.zeros(shape=(2, 3)) + 1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
from random import random as random_py
def builtin_random_single(n_runs):
    for _ in range(n_runs):
        random_py()

n_runs = 1000000
%prun builtin_random_single(n_runs)

         1000775 function calls (1000769 primitive calls) in 0.248 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      2/1    0.094    0.047    0.012    0.012 __init__.py:244(fun)
       14    0.057    0.004    0.087    0.006 socket.py:623(send)
  1000000    0.053    0.000    0.053    0.000 {method 'random' of '_random.Random' objects}
        4    0.030    0.007    0.045    0.011 {method 'control' of 'select.kqueue' objects}
        1    0.007    0.007    0.011    0.011 3304244467.py:2(builtin_random_single)
      2/1    0.004    0.002    0.011    0.011 {built-in method builtins.exec}
        1    0.003    0.003    0.006    0.006 {method 'execute' of 'sqlite3.Connection' objects}
        4    0.000    0.000    0.000    0.000 attrsettr.py:66(_get_attr_opt)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        8    0.000    0.000    0.094    0.012 {method 'run' of '_contextv